### ISSUE TITLE
Missing voice line in intro scene

### ISSUE THREAD

**Issue by RoyaltyRogue** [deviant-dev/ds-issues#103]
**The bug**
At the intro scene there is a missing voice line. She doesnt say "shake your head for yes"
**To Reproduce**
Open the game

**Expected behavior**
She says shake your head for yes.

**System**
 Device:  keyboard & mouse
 - Version: [e.g. 22]
Video
https://imgur.com/a/PUSSZt2

**Comment by Ropelopunny** [comment]
Issue occurred with version 2.0.4. Player reported that after uninstalling and reinstalling the issue was resoled. Was unable to duplicate on multiple computers. Closing
