### ISSUE TITLE
HM reward - Spank line during reward

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#104]
**Describe the bug**
   - During the Head Mistress reward, she will make a statement about the players ass being in distress, even though she is not spanking the player

**To Reproduce**
 - Play through the Head Mistress reward

**Expected behavior**
   - For the HM not to make a comment about the players ass being in Distress when not being spanked

**Screenshots**

**System (please complete the following information):**
 - VR Device: keyboard & mouse
 - Version: 2.0.5

**Additional context**

**Comment by Ropelopunny** [comment]
![20201126164536_1](https://user-images.githubusercontent.com/60497088/100403506-1772e780-302d-11eb-9b54-1aa6e34f8e09.jpg)

**Comment by HeadphoneTaco** [comment]
The cheeks comment is about the player's face, not ass cheeks. It's one of the possible lines when the Headmistress comments about the player being embarrassed.
