### ISSUE TITLE
Goddess Scene - No door collision

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#105]
**Describe the bug**
  - Players can again move behind the door and clip through it

**To Reproduce**
  - When playing with mouse and keyboard move toward the door, the door does not have collision so player can clip through it 

**Expected behavior**
  - The player should not be able to move and clip behind the door 

**Screenshots**
![20201126174115_1](https://user-images.githubusercontent.com/60497088/100403655-759fca80-302d-11eb-8063-ca61b086296e.jpg)

**System (please complete the following information):**
 - VR Device: [e.g. keyboard & mouse
 - Version: 2.0.5

**Additional context**

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
