### ISSUE TITLE
Limit players movement during Yuki intro

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#106]
**Is your feature request related to a problem? Please describe.**
Player can move around in desktop mode during the Mistress Yuki intro scene, and the player can move inside of either Mistress Yuki or Nega Yuki Model, seeing inside the models

**Describe the solution you'd like**
Limit movement in desktop mode so players can not move inside the models of Yuki and Mistress Yuki

**Describe alternatives you've considered**
   Stopping the movement in which the player can move inside the models

**Additional context**

**Comment by HeadphoneTaco** [comment]
Closing due to age
