### ISSUE TITLE
When opening the demo, it does not open on my headset and i have to play on my monitor. I am using oculus link with my quest 2

### ISSUE THREAD

**Issue by joemama6930** [deviant-dev/ds-issues#108]
**Describe the bug**

**To Reproduce**
2. Choose '....'
3. Try to '....'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - VR Device: [e.g. Oculus Rift, Vive Index, keyboard & mouse]
 - Version: [e.g. 22]

**Additional context**

**Comment by deviant-dev** [comment]
@joemama6930 You need SteamVR installed. Some people have need to run SteamVR first before running the game. 

Does this still happen when you have SteamVR running?

**Comment by joemama6930** [comment]
Hi, I realized this yesterday actually and was able to get it to work. I
just didn't realize that I needed steam VR

Thanks

**Comment by deviant-dev** [comment]
Great! I'm glad you figured it out. We hope you enjoy it!
