### ISSUE TITLE
Nega has no boots during 'edging and bootworship' scene

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#109]
**Describe the bug**

**To Reproduce**
2. Choose '....'
3. Try to '....'

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - VR Device: [e.g. Oculus Rift, Vive Index, keyboard & mouse]
 - Version: [e.g. 22]

**Additional context**

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
