### ISSUE TITLE
Nega's panties clipping

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#110]
**Is your feature request related to a problem? Please describe.**
   When the player is asked to move in closer to smell Nega's crotch the model/texture for the panties looks off

**Describe the solution you'd like**
  Updating the texture/model so it looks better in that position up close since the player is asked to put their face right in front.

**Describe alternatives you've considered**
   Nega could always not wear panties, but the butler might have to work overtime cleaning the floors

**Additional context**
![20210131221937_1](https://user-images.githubusercontent.com/60497088/106411799-1470ea80-6414-11eb-9a82-dda6341022c1.jpg)

**Comment by ThatCuteEevee** [comment]
Please Verify if still clipping or if thats how Nega's panties are designed

![20210628122105_1](https://user-images.githubusercontent.com/60497088/123673608-abe53880-d80e-11eb-8c60-85f364ca1e2d.jpg)

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
