### ISSUE TITLE
Soft lock - Nega Yuki Boot lick

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#111]
**Describe the bug**

**To Reproduce**
 - Get two skulls and a cup
 - Get boot worship scene

**Expected behavior**
   - Nega should identify that the player is licking her boot

**Screenshots**
![20210131222143_1](https://user-images.githubusercontent.com/60497088/106412183-15eee280-6415-11eb-922a-c8e49115bfb5.jpg)

**System (please complete the following information):**
 - VR Device: Valve Index
 - Version: 2.0.8

**Additional context**

**Comment by Ropelopunny** [comment]
Issue confirmed to occur in desktop mode as well

**Comment by HeadphoneTaco** [comment]
Confirmed, initial bootlicking pose recognition is successful; but continuing to lick Nega's boots does not work with head movements. Tested on desktop.

**Comment by deviant-dev** [comment]
Looks like this is fixed in the latest.

**Comment by HeadphoneTaco** [comment]
Confirmed, appears to be fixed as of Ver 2.1.0

**Comment by HeadphoneTaco** [comment]
Closing 'caused fixed, yo
