### ISSUE TITLE
Animation - Goddess's foot not on slave - Goddess intro

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#112]
**Is your feature request related to a problem? Please describe.**
  During the Goddess intro scene, There is a gap between the Goddess's foot and the slaves back, most likely because that gap was previously taken up by the boots the Goddess used to but no longer wears during the scene

**Describe the solution you'd like**
   For the Goddess's foot to press against the slave's back

**Describe alternatives you've considered**

**Additional context**
![20210201013808_1](https://user-images.githubusercontent.com/60497088/106424283-eb5e5300-642f-11eb-97ca-3f9a4e4ebb06.jpg)

*EDIT*
   After further testing the boot is missing in spots it should not be, so this is more of the bug being that the boot is missing**

![20210201013806_1](https://user-images.githubusercontent.com/60497088/106493406-1627c600-6487-11eb-9719-123911b15384.jpg)

![20210201112245_1](https://user-images.githubusercontent.com/60497088/106493417-188a2000-6487-11eb-8a80-df48718820f0.jpg)

**Comment by HeadphoneTaco** [comment]
What version of the game did this occur in? I don't see the bug, when testing on the most recent Master branch

**Comment by Ropelopunny** [comment]
2.0.8 on steam

**Comment by HeadphoneTaco** [comment]
Hmm, when I'm in-game on most recent master, the version is also 2.0.8

**Comment by ThatCuteEevee** [comment]
The Goddess's boot is on and no longer floats but there is still a bit of a gap between the foot and slaves back in 2.1.0+145

**Comment by HeadphoneTaco** [comment]
Confirmed, the gap is a minor issue at this point; can be fine tuned later. Updating Validate status.

**Comment by HeadphoneTaco** [comment]
Scratch that, closing bug.
