### ISSUE TITLE
Subtitle bug - Missing "...?" prompt.

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#113]
**Describe the bug**
   In certain scenes the "...?" prompt does not show up in the subtitles to advise the player when to respond.

**To Reproduce**
 Have subtitles on.  Issue occurs couple of scenes, see screenshots for spots the issue occurs

**Expected behavior**
   the "...?" subtitle prompt should show up any time the player is expected to answer the Mistress

**Screenshots**
![20210201110615_1](https://user-images.githubusercontent.com/60497088/106493560-4a02eb80-6487-11eb-971d-31a54478c6b9.jpg)

![20210201112043_1](https://user-images.githubusercontent.com/60497088/106493571-4f603600-6487-11eb-9980-5655228eefad.jpg)

![20210201112417_1](https://user-images.githubusercontent.com/60497088/106493587-54bd8080-6487-11eb-99d0-6a7cb52fa7e6.jpg)

![20210201113904_1](https://user-images.githubusercontent.com/60497088/106493597-5a1acb00-6487-11eb-9bd8-790048c6005f.jpg)

![20210201115103_1](https://user-images.githubusercontent.com/60497088/106493603-5d15bb80-6487-11eb-9e8a-a054e23fbf9f.jpg)

**System (please complete the following information):**
 - VR Device: Desktop
 - Version: 2.0.8

**Additional context**

**Comment by HeadphoneTaco** [comment]
I can see the "...?" prompt, on version 2.0.8 on most recent master

![easy_right](https://user-images.githubusercontent.com/12089633/106501926-f392ae80-6480-11eb-80d3-3a218f753c52.png)

**Comment by Lewder** [comment]
Seems to be fixed in build 124. Played through the entire tutorial without finding any instances of it.
