### ISSUE TITLE
Nega groping air

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#116]
During yuki's intro, nega is supposed to grope the player's crotch. she doesn't advance all the way forward towards the player, and gropes the air in front of the player. When nega resumes groping, she successfully gropes the player's crotch.

**Comment by Lewder** [comment]
Issue still present in build 124 for both masculine and feminine appearances.

**Comment by ThatCuteEevee** [comment]
Issue confirmed resolved in 2.1.0+139. Closing
