### ISSUE TITLE
female point of view 

### ISSUE THREAD

**Issue by agjkp** [deviant-dev/ds-issues#118]
when u get roll nega dice x3 cup
she keeps talking about the strap-on but the fact that it's there already make no seance it would be better
if she would actually put the strap-on on you like a double side dildo a part goes in you and the other is out or if she would use it on u like she put's it on and fucks u in the pu**y
and when u meet her the first time she always refer to u as u have di*k
it would be better if she rub a pussy instead of a di*k

these are just like my personal opinion as a girl point of view

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
