### ISSUE TITLE
Door collision allows for hide and seek with Goddess

### ISSUE THREAD

**Issue by KingOfEggs** [deviant-dev/ds-issues#15]
**Describe the bug**
The door behind the player in the Goddess' chamber doesn't have the proper collision, allowing you to walk inside the door.

**To Reproduce**
1. Start the game and play to the Goddess' chamber.
2. Walk into the door that is behind the player when they spawn in.

**Expected behavior**
The door's collision will stop the player *before* they begin osmosis.

**Screenshots**
![door collision 1 5](https://user-images.githubusercontent.com/60536182/73599846-1dcc2c00-450e-11ea-8001-08873aa5027d.gif)

**System (please complete the following information):**
 - VR Device: K&M
 - Version: 51
 - System: Win10 64-bit

**Comment by Ropelopunny** [comment]
Issue still occurs in 2.0.3 with mouse and keyboard

**Comment by Ropelopunny** [comment]
Confirmed issue resolved in Ver. 2.0.4. Closing
