### ISSUE TITLE
Decline to give Nega a bloodstone issue

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#18]
**Describe the bug**
Declining to give Nega-yuki the bloodstone kicks you to the credits screen without the ending Goddess scene

**To Reproduce**
   - Decline giving the bloodstone to Nega-yuki twice.

**Expected behavior**
   - Domina stated it should do more, and Deviant stated that Nega should tell on the player and still end the scene getting in trouble

**Screenshots**
![20200201191657_1](https://user-images.githubusercontent.com/60497088/73601511-06eb0100-4531-11ea-9206-0dc6f7d64638.jpg)
![20200201191701_1](https://user-images.githubusercontent.com/60497088/73601512-094d5b00-4531-11ea-80b6-4e90c864e202.jpg)
![20200201191706_1](https://user-images.githubusercontent.com/60497088/73601513-0b171e80-4531-11ea-915d-c612375365e7.jpg)
![20200201191708_1](https://user-images.githubusercontent.com/60497088/73601516-0ce0e200-4531-11ea-94c8-51d723a958ad.jpg)
![20200201191717_1](https://user-images.githubusercontent.com/60497088/73601517-110cff80-4531-11ea-9721-9b983c5041ab.jpg)
![20200201191719_1](https://user-images.githubusercontent.com/60497088/73601519-1702e080-4531-11ea-8880-9f73e7497326.jpg)
![20200201191721_1](https://user-images.githubusercontent.com/60497088/73601521-18cca400-4531-11ea-847f-2db66dee35be.jpg)
![20200201191725_1](https://user-images.githubusercontent.com/60497088/73601523-1ff3b200-4531-11ea-977e-321835e60ab8.jpg)
![20200201191732_1](https://user-images.githubusercontent.com/60497088/73601525-2d10a100-4531-11ea-9a87-3bc6ec0b5113.jpg)

**System (please complete the following information):**
 - VR Device: Index HMD, controllers, and lighthouses (2 of them)
 - GPU: GTX 2060 Driver 441.87
 - Version: Build 51

**Additional context**

**Comment by Ropelopunny** [comment]
Issue Partially resolved in Build 55, though Nega's lines do not play only the subtitles of the lines come up

**Comment by deviant-dev** [comment]
Closing this bug as the missing VO lines are a separate issue (also being worked on now).

Thanks so much for all the very clear bug reports, @Ropelopunny!
