### ISSUE TITLE
Subtitles stick around for credits map

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#19]
**Describe the bug**
  - Completing the ending scene with either Nega-Yuki(see issue#:18 https://github.com/deviant-dev/ds-issues/issues/18) or the Goddess does not bring down that last scenes subtitle and they remain in the credits map

**To Reproduce**
 - Complete the Goddess or Nega Yuki Scene and look behind the player position 

**Expected behavior**
   The subtitles should disappear after the ending scene completes

**Screenshots**
![20200201191746_1](https://user-images.githubusercontent.com/60497088/73601626-f3409a00-4532-11ea-90c1-6cc1832ccd1b.jpg)
![20200201200804_1](https://user-images.githubusercontent.com/60497088/73601628-f5a2f400-4532-11ea-98b7-fae1e834cd4c.jpg)

**System (please complete the following information):**
 * VR Device: Index HMD, controllers, and 2.0 lighthouse
* GPU: GTX 2060 Driver 441.87
* Version: Build 50

**Additional context**

**Comment by HeadphoneTaco** [comment]
The spelling of 'Former' needs a tweak as well

**Comment by deviant-dev** [comment]
Ha! Good catch! :)
