### ISSUE TITLE
Selection pointer lag

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#26]
**Describe the bug**
   When playing in VR mode and the Journal is open the pointer/selector lags and does not keep up with the movement of the players hands, with a delay that ranges between 1-2 seconds. 

**To Reproduce**
Open the Journal in VR mode and move the pointer

**Expected behavior**
The pointer should move with the players hand to allow for easier selection of journal options

**Screenshots**
Screenshots/gifs have issues showing the lag

**System (please complete the following information):**
* VR Device: Index HMD, controllers, and 2.0 lighthouse
* GPU: GTX 2060 Driver 442.19
* Version: Demo Build 4

**Additional context**

**Comment by deviant-dev** [comment]
Should be fixed in the next build.
