### ISSUE TITLE
"Crazy Legs" Goddess

### ISSUE THREAD

**Issue by KingOfEggs** [deviant-dev/ds-issues#27]
**Describe the bug**
Goddess' leg model is getting very warped in an early animation

**To Reproduce**
Start the game as normal and play up to the intro with the Goddess

**Expected behavior**
Her leggy not to breaky

**Screenshots**
![goddess crazy legs](https://user-images.githubusercontent.com/60536182/74078857-18cb1900-49f5-11ea-928d-ad2d286fdf41.png)

**System (please complete the following information):**
 - VR Device: K&M
 - Version: 55
 - OS: Win10

**Comment by Ropelopunny** [comment]
Report reviewed, still relevant.

**Comment by Ropelopunny** [comment]
Confirmed animation does not show model error in animation on 2.0.5
