### ISSUE TITLE
Option to turn snap turn off

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#28]
**Is your feature request related to a problem? Please describe.**
   When playing with index controllers, the thumbs can easily slip onto the track pad and make the player snap turn till they lift their thumb up, by which point they might have already done a 180 turn.

**Describe the solution you'd like**
 An ability to turn snap turning off in the journal

**Describe alternatives you've considered**
   this could be turned off in Steams controller binding system but having an option to turn it off in the journal will help when play testing but also help players that may not be savvy enough to turn the trackpad controls off in the controller binding software.

**Additional context**

**Comment by deviant-dev** [comment]
This'll be in the next build! Thanks for the suggestion, @Ropelopunny
