### ISSUE TITLE
Perform Swipe_Hand

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#34]
**Describe the bug**
Animation will not trigger in Unity, but there is no associated error in the console.

**To Reproduce**
1. Go to HM_reward_exhibitionism and give her a bloodstone when she asks for it.

**Expected behavior**
Once player agrees to give it, she should perform swipe hand but she simply goes into the next animation listed in Ink.

**Comment by HeadphoneTaco** [comment]
Fixed the issue; had to use a ` /wait 2 ` command, though. Not the best fix, but seems to be the easiest solution for now. Attempted to make HM's hand swiping a separate stitch or knot, still wouldn't work properly. Not sure what's going on with that. Moving to Validate.

**Comment by HeadphoneTaco** [comment]
Closing due to age
