### ISSUE TITLE
Goddess Eyes Closed

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#39]
**Describe the bug**
Goddess's Eyes in the Character Animation tool are closed during 
/perform idle_fake_annoyed amused
Her eyes seem to blink open as the animation starts again

**To Reproduce**
1. Use Character Animation Tool
2. Set animation to idle_fake_annoyed
3. Set emotion to amused

**Expected behavior**
Goddess's eyes to not be closed

**Screenshots**

![Goddess_Eyes](https://user-images.githubusercontent.com/12089633/79153772-a3305000-7d8b-11ea-9032-b6298fe36b3f.gif)

**System (please complete the following information):**
 - Win 10 M+KB
 - Character Animation Tool 3.0

**Comment by deviant-dev** [comment]
It looks like this got fixed along the way somewhere.
