### ISSUE TITLE
do_now_leave Rotating Unexpectedly

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#40]
**Describe the bug**
If the do_now_leave animation is left in a loop state, the character model will slowly turn away from the player; approximately 9.7 degrees per animation cycle. If another animation is played after this rotation occurs, the next animation doesn't recenter; the character could be facing the complete opposite direction and still continue with the script.

**To Reproduce**
1. Use Character Animation Tool
2. Set animation to do_now_leave
3. Set animation to loop
4. Wait a bit for the rotation to be noticeable
5. Change animation to something else

**Expected behavior**
Expected the character models to not change their orientation significantly after a animation cycle; OR, if the change is desired, for the engine to reset the character orientation to starting postion when initiating change of animation.

**Screenshots**
![do_now_leave_cycle-frames](https://user-images.githubusercontent.com/12089633/79497064-53989100-7fe4-11ea-85a9-5a4115a05d4c.gif)
![bugFinal](https://user-images.githubusercontent.com/12089633/79497102-627f4380-7fe4-11ea-8576-e05fce2bb1ec.png)

**System:**
 - Win 10 M+BK
 - Char Tool Ver. 3

**Comment by deviant-dev** [comment]
Wow, great catch!

**Comment by HeadphoneTaco** [comment]
Thanks! Now hoping that animation isn't anywhere that was a loop condition lol

**Comment by deviant-dev** [comment]
Should be fixed in the next build.
