### ISSUE TITLE
do_circle_player_step_down Twitching

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#41]
**Describe the bug**
The character models stand and swing left arm slightly, with left arm extended down towards the ground. The character model then resets back to starting postion, causing the character to twitch. The whole cycle takes approximately 3.5 seconds.

**To Reproduce**
1. Use Character Animation Tool
2. Set animation to do_circle_player_step_down
3. Watch 'em twitch

**Expected behavior**
An animation of some sort

**Screenshots**
![do_circle_player_step_down_cycle-frames](https://user-images.githubusercontent.com/12089633/79499854-cdcb1480-7fe8-11ea-809a-b65aae7a3f10.gif)

**System (please complete the following information):**
 - Win 10 M+KB
 - Char Tool Ver 3

**Comment by deviant-dev** [comment]
Ah, yes. This is supposed to be the Goddess stepping down and circling the
player when she's examining them. Thanks for logging that. It's on my list
as a part of the animation cleanup pass.

**Comment by HeadphoneTaco** [comment]
There's several more bugs I've found while going through the animation list, I'll post them all once I've completed my study of them.

**Comment by HeadphoneTaco** [comment]
Issue still present, on the to-do list for animation creation

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
