### ISSUE TITLE
HM_Intro_Slave_Butt_Wonky

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#42]
**Describe the bug**
The slave's butt in HM Intro is not looking right

**To Reproduce**
Go to HM intro, watch her discipline the slave

**Expected behavior**
No funky butts

**Screenshots**
![slave_butt](https://user-images.githubusercontent.com/12089633/80259702-714ca280-8643-11ea-80fa-4904f5603d2d.png)

**System (please complete the following information):**
-Win 10 KB+M
-Testing build of Domsim

**Comment by Ropelopunny** [comment]
This issue has been resolved in current builds, closing
