### ISSUE TITLE
Nega Lip Animation Issue-Useless Dick

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#43]
**Describe the bug**
Nega's lips do not move in the way that they should during a voice line

**To Reproduce**
1. Go to nega_reward_forcedsex
2. Choose no, when asked if you want to cum with Nega
3. See uploaded .gif

**Expected behavior**
Nega's lips to not imitate a xenomorph

**Screenshots**
![Useless_Dick (2)](https://user-images.githubusercontent.com/12089633/82379234-caf68180-99e3-11ea-93f1-0cfa13b60216.gif)

**System (please complete the following information):**
 - Win 10, M+BK
 - Threshold Ver 68

**Comment by deviant-dev** [comment]
Yikes! That one was really bad. Good catch, @HeadphoneTaco. It should be fixed in the next build.
