### ISSUE TITLE
Texture Error for Lantern in Goddess's chamber

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#44]
**Describe the bug**
One of the panels of a lantern in Godess's chamber is wonky. Issue is present in all level of graphics detail; toggling post fx or anti-aliasing makes no difference.

**To Reproduce**
1. Go to Goddess's chamber
2. Look up and see the texture error

**Screenshots**
![Lantern](https://user-images.githubusercontent.com/12089633/82843302-01c41000-9e9a-11ea-8475-63a49a845ab1.png)

**System (please complete the following information):**
-Win 10
-M+KB

**Comment by deviant-dev** [comment]
@HeadphoneTaco Do you mean the pane on the left side? I think it's shiny reflecting the light from the standing candelabra and has a worn surface. As designed, I think.

Feel free to reopen if it's something else you are referring to.
