### ISSUE TITLE
Nega Yuki Finish

### ISSUE THREAD

**Issue by DaedelusMuse** [deviant-dev/ds-issues#45]
**Her legs are weird**
When Nega Yuki "finishes", her legs clip through her body

**To Reproduce**
1. Go to 'Nega Yuki Forced Scene'
2. Progress through to the end
3. Watch her legs when she "finishes"

**Expected behavior**
Maybe change the positioning? I'm no programmer, so I don't know.

**Screenshots**

**System (please complete the following information):**
 - Laptop (details in screenshot) 
![Annotation 2020-06-10 034426](https://user-images.githubusercontent.com/66719724/84241057-ed545a00-aacc-11ea-8be3-ed4ba4e738f1.png)

 - Version: [0.0.1]

**Additional context**

**Comment by deviant-dev** [comment]
Thanks for the bug report! I'll look into that soon.

**Comment by deviant-dev** [comment]
That was a really bad one! All fixed up here in v.0.0.2. Thanks again, @DaedelusMuse!
