### ISSUE TITLE
Head Mistress punishment scene floor

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#50]
**Describe the bug**
The head Mistress, the slave, and the player hover above the floor and desk in the Head Mistress punishment scene

**To Reproduce**
 - Play scene normally

**Expected behavior**

**Screenshots**
![20200619132440_1](https://user-images.githubusercontent.com/60497088/85164798-de8b4700-b232-11ea-97df-c0f4af7293da.jpg)

![20200619132410_1](https://user-images.githubusercontent.com/60497088/85164832-e8ad4580-b232-11ea-90d2-c1eb93021f95.jpg)

![20200619120142_1](https://user-images.githubusercontent.com/60497088/85164863-f367da80-b232-11ea-8112-e9ee62be22be.jpg)

**System (please complete the following information):**
 - VR Device: Oculus Quest Link and Valve index with 2.0 light houses
 - Version: Steam version 1.1.0

**Additional context**
  - Used OVR to quickly re-calibrate the floor and the same issue occurred. Same issue does not occur in the Intro goddess scene or in the Nega Yuki scene

**Comment by Ropelopunny** [comment]
Issue also occurs in the early access build of the exhibition scene. Playspace mover was used to get better pics. Note: Desk and chair are also floating above the floor, though it is hidden by the center circular rug. Can also confirm that this seems to still effect the present stone pose

![20200812124551_1](https://user-images.githubusercontent.com/60497088/90049891-79d4f180-dca3-11ea-8a8a-ed1d2d1ab9a2.jpg)

![20200812124616_1](https://user-images.githubusercontent.com/60497088/90049911-7f323c00-dca3-11ea-8f6d-549732b8f509.jpg)

![20200812124623_1](https://user-images.githubusercontent.com/60497088/90049928-88230d80-dca3-11ea-8f5d-18ea6b874b99.jpg)

![20200812124648_1](https://user-images.githubusercontent.com/60497088/90049954-8eb18500-dca3-11ea-81e2-43dcd78440f6.jpg)

![20200812124657_1](https://user-images.githubusercontent.com/60497088/90049986-98d38380-dca3-11ea-84dc-017d725be900.jpg)

**Comment by Ropelopunny** [comment]
Additional Note: hovering occurs even with placespace mover turn off and not in use, and reconfirmed that this issue is not occurring in other scenes with or without playspace mover turned on

**Comment by Ropelopunny** [comment]
Issue when player is on desk is more pronounced in build 81

![20200815134122_1](https://user-images.githubusercontent.com/60497088/90318795-fd3f4e80-df00-11ea-88b8-a5025a16cb91.jpg)

**Comment by Ropelopunny** [comment]
Issue still occurs in build #89

**Comment by Ropelopunny** [comment]
In build #95 the slave is no longer floating above the desk, but as a consequence since the Head Mistress is still floating bit from the floor she is swatting above the slave's rear

**Comment by Ropelopunny** [comment]
Tianova also repots noticing the HeadMistress Swatting the air and not slave

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
