### ISSUE TITLE
Can't select gender statues

### ISSUE THREAD

**Issue by deviant-dev** [deviant-dev/ds-issues#52]
**Describe the bug**
From Jlp#6678: "I'm stuck in the statue area and not able to move from there, where you choose gender."

**To Reproduce**
1. Play through the into to the statue gender selection step. 
2. Try and select a gender (maybe put hands inside statues?)
3. Notice they can't be selected

**Expected behavior**
Gender is selected and I'm able to continue.

**Comment by Ropelopunny** [comment]
This issue is curently resolved in current builds, closing
