### ISSUE TITLE
DomSim unable to run

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#53]
**Describe the bug**
First reported by @Scyrus42

Unable to run DomSim on an RTX 2070, even though other games are able to run fine. Cannot disable VR mirror. 

**To Reproduce**
Try and start DomSim from either desktop or within Steam VR Home Area

**Expected behavior**
DomSim should run without issues

**System (please complete the following information):**
Steam VR Version: 1.12.5
DomSim Version: Latest Steam Build
Vive 2nd Gen?(Forgot to ask)

**Additional context**
HMD is plugged into RTX 2070, 2 monitors plugged into motherboard as DP-HDMI converters are not available

**Comment by deviant-dev** [comment]
I'm not sure where they reported this, but I'll need more info to figure out what's going on. Can Scyrus42 send us his Player.log file?

It should be here:
`%LOCALAPPDATA%\LocalLow\deviant.tech\Dominatrix Simulator\Player.log`

**Comment by Ropelopunny** [comment]
Issue has been tested on an RTX 2060 and an RTX 2080, issue not replicable in current builds. Need further information.

**Comment by Ropelopunny** [comment]
Last day for response from player before issues is closed, if we do not hear back after today issue will be closed

**Comment by Ropelopunny** [comment]
Unable to hear back from the player that reported the issue, Closing
