### ISSUE TITLE
Cock Instead of Vagina

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#54]
During the Yuki Intro - When Nega goes to stroke a player's 'vagina', an in game penis is there instead. I was playing as female. I did not manually select vagina from the journal, so was assigned a default genitalia.

VO references 'girl' and 'cunt'.

**Expected behavior**
Should be a pelvis with a vagina for the player when playing with female genitalia.

**Comment by deviant-dev** [comment]
Should be fixed in build #96+

**Comment by Ropelopunny** [comment]
Issue confirmed resolved in current steam build, closing
