### ISSUE TITLE
Nega's position resets and then resume during stroking

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#55]
Yuki Intro - during stroking sequence, Nega slides away from player back into her original starting position, and then again back to the player and resumes stroking. 

**To Reproduce**
1. Playing game as default female.
2. Answered yes to wanting to be stroked.

**Expected behavior**
Nega should stay stroking the player through the entire VO sequence

**Comment by DevilishDomina** [comment]
There were lots of extra animations in breaking up the caress_genitals sequence. These have been removed and she should stay stroking you through the whole thing now.

**Comment by Ropelopunny** [comment]
Issue continues in build 95

**Comment by Ropelopunny** [comment]
Confirmed issue is resolved in build 2.0.1. Closing
