### ISSUE TITLE
Headmistress' tongue is shiny

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#56]
Seems like there is a weird light inside her mouth that makes her tongue and teeth shiny. It's very distracting.

First encountered it when the HM intro shifts to position her in front of player and begins talking to them.

**Expected behavior**
Should be dark and shadowed.

**Screenshots**
![image](https://user-images.githubusercontent.com/41113516/85937794-f2cdf300-b95a-11ea-9b8a-2b0fa25a60ef.png)

**Comment by Ropelopunny** [comment]
Confirmed issue is resolved in steam build 2.0.1
