### ISSUE TITLE
HM voice level and location

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#57]
**Describe the bug**
When the HM is repositioned on the far side of the theatre for the punishment spanking scene, the volume of her voice does not change to indicate it is farther away.

**Expected behavior**
Her voice should get louder or softer depending on her position. When across the room, it should sound like it's being carried across a distance rather than up close.

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
