### ISSUE TITLE
Top floor audience clipping through balcony

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#64]
**Describe the bug**
Some Audience members on the very top row bend over far enough they clip through the balcony wall

**To Reproduce**
Play out the scene normally

**Expected behavior**
Audience members on the top floor should not clip through balcony

**Screenshots**
![20200815133655_1](https://user-images.githubusercontent.com/60497088/90319492-ad638600-df06-11ea-8804-18a7e9a24c30.jpg)

**System (please complete the following information):**
 - VR Device: Valve index HMD and controllers. 2.0 lighthouses
 - Version: Build 81

**Additional context**

**Comment by HeadphoneTaco** [comment]
Closing due to irrelevance at this present time
