### ISSUE TITLE
Different direction - Oculus Quest

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#66]
**Describe the bug**
At the beginning of a scene or scene change, the player will not be pointing the correct direction. An example being Facing away from the goddess when she becomes a giant, or having back turned on Mistress Yuki at the beginning of the Mistress Yuki intro scene

**To Reproduce**
Using an oculus quest with link cable. Does not replicate the issue on Valve index.

**Expected behavior**
The player at the beginning of a scene should be facing the direction they are supposed to at the beginning of the scene

**Screenshots**
 N/A

**System (please complete the following information):**
 - VR Device: Oculus Quest
 - Version: Build 81

**Additional context**
 - Issue can be worked around by using the thumb stick to rotate to the correct position.

**Comment by HeadphoneTaco** [comment]
Unable to confirm or deny, do not have access to Oculus hardware for testing

**Comment by HeadphoneTaco** [comment]
Closing due to inconsistency of bug replication
