### ISSUE TITLE
Soft lock after Nega-yuki dice roll

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#68]
**Describe the bug**
   After giving bloodstone to Nega-Yuki for the dice roll, after rolling the dice the scene is soft locked and does not continue. The player is stuck and has to quit the game and restart

**To Reproduce**
 - Play through the Nega-Yuki scene as normal.

**Expected behavior**
  - The scene should continue after the dice roll

**Screenshots**
![20200815220912_1](https://user-images.githubusercontent.com/60497088/90325059-b96e3880-df44-11ea-9e44-926a423e4d2e.jpg)

![20200815220914_1](https://user-images.githubusercontent.com/60497088/90325062-c1c67380-df44-11ea-927d-121ff3335e26.jpg)

**System (please complete the following information):**
 - VR Device: Valve Index HMD and controllers, 2.0 light houses
 - Version: Build 81

**Additional context**

**Comment by Lewder** [comment]
I got the same soft lock when doing the dice roll as part of Nega's reward in the game loop. Completely unable to interact with the dice after that point.

**Comment by deviant-dev** [comment]
I'm not able to reproduce this one in VR or KB&M. I'm wondering if I'm not doing things in the same order as you two are? Perhaps a video of it happening? Also, a Player.log might help as well.
`%appdata%\..\LocalLow\deviant.tech\Dominatrix Simulator\Player.log`

**Comment by Ropelopunny** [comment]
Issue no longer occurring in build #95, it is worth taking a look to see if the error mentioned in 'Nega Dice Binding Issue #76' is still occurring
