### ISSUE TITLE
"Divine Engine" Black Room

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/ds-issues#69]
**Describe the bug**
The game soft locks when entering the room of the "Divine Engine" Mistress. Journal is unusable.

**To Reproduce**
Enter the Divine Engine's room.

**Expected behavior**
Expected to see the placeholder Mistress's room.

**System (please complete the following information):**
 - VR Device: Valve Index + Knuckle Controllers + 2.0 Stations
 - Version: 81

**Comment by Lewder** [comment]
This is issue #69. _Nice._

**Comment by Ropelopunny** [comment]
Can confirm issue still occurs in build #89.

Valve index HMD, Valve index controllers, Index 2.0 light houses

**Comment by Ropelopunny** [comment]
This issue is confirmed resolved in current builds
