### ISSUE TITLE
Vagina dialogue when it should be penis

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/ds-issues#71]
**Describe the bug**
The Mistresses will sometimes talk to you as though you have a vagina even when you've selected penis.

**To Reproduce**
1. Choose all feminine appearances/voice/name but have a penis
2. Switch all feminine appearances/voice/name and keep the penis
3. Mistresses will sometimes refer to you as though you have a vagina. I originally had it happen during the first scene with with Yuki/Nega

**Expected behavior**
Expected Mistresses to refer to my penis.

**System (please complete the following information):**
 - VR Device: Index + Knuckle Controllers + 2.0 base stations
 - Version: 81

**Comment by DevilishDomina** [comment]
We think we've found all instances where it's referencing a vagina when a player has selected penis.

If any additional lines are found, please give us the exact dialogue line so we can fix that specific issue.
