### ISSUE TITLE
Using journal for movement stops Nega from moving

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/ds-issues#72]
**Describe the bug**
In the first attic scene, using the journal for movement prevents Nega from moving. She stays leaning against the wall and all dialogue continues as though she moved.

**To Reproduce**
1. Go to first attic scene
2. Open journal
3. Select "Move"

**Expected behavior**
Expected the scene to continue as normal

**System (please complete the following information):**
 - VR Device: Index + Knuckle Controllers + 2.0 base stations
 - Version: 81

**Comment by deviant-dev** [comment]
I want's able to reproduce this one, @Lewder. Can you test with the latest build ([1.2.0+93](https://deviantdev.itch.io/domsim-threshold-beta/patreon-access))?

Feel free to re-open the bug if it's still happening.

Thank you so much for logging these, btw! 🙏
