### ISSUE TITLE
Yuki puppy play scene ends when using journal for puppy on back "yes" pose

### ISSUE THREAD

**Issue by Lewder** [deviant-dev/ds-issues#73]
**Describe the bug**
I was able to make this happen during two different situations which called for the puppy on back "yes" pose during the Yuki reward scene.

**To Reproduce**
1. Play through Yuki's puppy reward scene
2. Use the journal for the puppy on back "yes" pose
3. Yuki will reply something to the effect of "Alright then if you're sure"
4. You will either be taken back to the main chamber or to the Goddess' chamber

**Expected behavior**
Expected the journal entry to work as a replacement for the pose.

**System (please complete the following information):**
 - VR Device: Index + Knuckle Controllers + 2.0 base stations
 - Version: 81

**Comment by deviant-dev** [comment]
@Lewder We've changed this scene quite a bit and haven't seen this behavior recently. Can you let us know if it's still happening for you in the latest build?

**Comment by uFarad** [comment]
> 
> 
> @Lewder We've changed this scene quite a bit and haven't seen this behavior recently. Can you let us know if it's still happening for you in the latest build?

Looks like it's fixed in this build.

**Comment by Lewder** [comment]
> 
> 
> @Lewder We've changed this scene quite a bit and haven't seen this behavior recently. Can you let us know if it's still happening for you in the latest build?

Looks like it's fixed in this build.
