### ISSUE TITLE
Having a reward when visiting Yuki breaks game

### ISSUE THREAD

**Issue by Joy2020TV** [deviant-dev/ds-issues#74]
If I have a reward, no matter what I pick, Yuki ends up promising a reward.  At this point she disappears from the screen, and tells you to get on your back.  However, the pose bubble shows "Pose Name" with no actual pose displayed.  Clicking Puppy Back on the journal does nothing to advance the game.  At this point you are locked in Yuki's room without her there and no way to continue except to reload or to quit.

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
