### ISSUE TITLE
Nega Dice Binding Issue

### ISSUE THREAD

**Issue by HeadphoneTaco** [deviant-dev/ds-issues#76]
**Describe the bug**
Error message in Unity console: 
"Missing function binding for external Nega Die"

**To Reproduce**
Load Unity

**Expected behavior**
No error messages

**Screenshots**
![image](https://user-images.githubusercontent.com/12089633/96523572-45495d00-1233-11eb-8c12-494ff2de1d32.png)

![image](https://user-images.githubusercontent.com/12089633/96523484-18954580-1233-11eb-81a3-4620e393f36c.png)

**System (please complete the following information):**
 -Win 10 64bit Home Edition
-Current windows security updates

This is likely related to the Nega Dice softlock bug, as reported by Ropey in  #68

**Comment by deviant-dev** [comment]
It looks like this is a setup issue? I'm not seeing it in my editor. Let me know if it's still happening and we can maybe do a screen debug session.

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
