### ISSUE TITLE
Nega Yuki Slap Not Registering

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#79]
**Describe the bug**
Nega Yuki slap during intro scene does not always register player action. It doesn't result in a success or failure and the scene will be frozen till player selects the result in the journal 

**To Reproduce**
Preforming the action. Multiple attempts were made to try to track down the exact cause such as head tilt or speed of the players head when snapping back but an exact way to duplicate this every time has not yet been found

**Expected behavior**
The head movement register as a slap

**Screenshots**
https://www.dropbox.com/s/x49c894h6vmy4te/Nega_slap.mp4?dl=0

**System (please complete the following information):**
 - VR Device: Valve index headset, Valve Index controllers, 2.0 lighthouses, running at 90hz
 - Version: 1.2.0+91

**Additional context**

**Comment by deviant-dev** [comment]
I've tested this in a loop for a while and wasn't able to reproduce it. (But it was fun having Nega beat the hell out of me! 😄)

I guess I'm putting this under 'Validate' until we aren't able to reproduce or have more info?

@Ropelopunny If it happens again, please send me the Player.log file from here!
`%appdata%\..\LocalLow\deviant.tech\Dominatrix Simulator\Player.log`

**Comment by Ropelopunny** [comment]
I am not able to replicate this on the current build either, closing
