### ISSUE TITLE
Intro Goddess scene lock

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#81]
**Describe the bug**
If the player exits the intro goddess scene then tries to load back in with the profile, it will not load and will be stuck in black screen

**To Reproduce**
1. Exit the Goddess scene at any point
2. Try to reload that point from that profile
3. screen will be blank black with no access to the journal, player has to exit and restart, then reset profile and start over

**Expected behavior**
The player should be able to load back into the Goddess Scene

**Screenshots**

**System (please complete the following information):**
 - VR Device: Valve index HMD and controllers, 2.0 light houses, 90Hz
 - Version: Build 92

**Additional context**

**Comment by Ropelopunny** [comment]
Forgot to note, the reason the profile has to be erased is because if the player closes the game and tries to reload, it will only load the skybox, but can now access the journal:

![20201021123039_1](https://user-images.githubusercontent.com/60497088/96756852-a6dc0980-13a2-11eb-9e33-f1025cbb9635.jpg)

![20201021123048_1](https://user-images.githubusercontent.com/60497088/96756860-ab082700-13a2-11eb-8eb5-2cbd1b903d53.jpg)

If the player tries to load a different profile regardless of where it was saved to it will load an all black scene but still have access to the journal:
![20201021123130_1](https://user-images.githubusercontent.com/60497088/96757269-3386c780-13a3-11eb-9641-1813daba786c.jpg)

The only way out is to reset the profile that is tied to the Goddess intro scene then close the game and reopen. It should be noted that to this issue occurring the Halloween costumes were not loading, so it might be a conflict from previous build to current one. Will do additional testing between the two builds to test for this possibility

**Comment by deviant-dev** [comment]
I figured this one out! There was an issue with variables being set incorrectly when saves were happening, so you'd end up in limbo trying to load the save. I've added in a bunch of additional handling for when the profile is corrupted and a better system for making sure the reload path variables are set correctly in ink.

Should be fixed in build #95

**Comment by Ropelopunny** [comment]
Confirmed resolved in build #95
