### ISSUE TITLE
Present stand pose - hand postion

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#82]
**Describe the bug**
In order to successfully register that the player is in the Present Stand pose, they need to have their hands up in the air instead of the back of their head 

**To Reproduce**
Going into a scene that requires the player to do stand pose

**Expected behavior**
  The pose figure shows the hands on the back of the head and not in the air, so the expectation is that hands should be on the back of the head not in the air

**Screenshots**
![20201021120935_1](https://user-images.githubusercontent.com/60497088/96748267-4dbaa880-1397-11eb-950d-8228915f8247.jpg)

**System (please complete the following information):**
 - VR Device: [e.g. Oculus Rift, Vive Index, keyboard & mouse]
 - Version: Build #92

**Additional context**
Issue does not occur with Present Kneel

**Comment by HeadphoneTaco** [comment]
Closing due to age
