### ISSUE TITLE
Head Mistress Ghost Spank

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#83]
**Describe the bug**
  The submissive the HeadMistress is punishing at the beginning plays the animation of being spanked but the Head Mistress does not play the animation of her spanking the sub, the result is the sub seeming to be spanked by an invisible force

**To Reproduce**
Play through the intro Head Mistress scene at the beginning when the submissive is being spanked

**Expected behavior**
   Either the submissive does not play animation of being spanked when not spanked by Head Mistress or Head Mistress plays the spanking animation to go with the being spanked animation of the sub.

**Screenshots**
https://www.dropbox.com/s/bjvn6hwqrvta0cz/HM_Ghost_Swat.mp4?dl=0

**System (please complete the following information):**
 - VR Device: Valve index headset and controllers, 2.0 lighthouses, 90hz refresh rate
 - Version: Build 93

**Additional context**

**Comment by HeadphoneTaco** [comment]
Hah! Casper is being a naughty boy

This is likely a code whoops where it was coded to spank x1 instead of spank xN, I'll look into it

**Comment by HeadphoneTaco** [comment]
Just played from the `Master` branch, this issue isn't there

**Comment by deviant-dev** [comment]
I haven't been able to repro this either. Can you validate it isn't happening for you in the latest, @Ropelopunny?

**Comment by Ropelopunny** [comment]
Verified issue is resolved in build #95
