### ISSUE TITLE
Delay Pose Assist Appearance

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#84]
**Describe the bug**
Often times, the pose assist appears before the player knows what their in game choices are and before the command has been given.

**To Reproduce**
1. Example: Headmistress tells the player to 'stand at attention', but the pose assist is there before she even starts her VO line.

**Expected behavior**
As a player, I want to hear the instructions before being given a visual indicator of how to pose. I want to be able to do this without being prevented from answering yes or no as soon as the Mistress starts to ask me a question. This is because I may know I want to say 'yes' right away and being able to do this maintains the pacing of the scene, but I want to be 'surprised' by the command and hear it verbally before it is given away visually.

**Additional context**
This has been raised by many playtesters / players in the past, but has not been listed as an issue yet.

**Comment by Ropelopunny** [comment]
In build 95 it no longer does this behavior when teaching the commands, but it still occurs when Head Mistress tests the players knowledge

**Comment by HeadphoneTaco** [comment]
Closing due to age
