### ISSUE TITLE
Game Crash at start of intro when changing gender options

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#85]
**Describe the bug**
   When starting build 94 for the first time, if it loads a new save and the player tries to load a different profile they are unable to, if they adjust their gender options from the beginning of the intro the game crashes.

**To Reproduce**
  - Boot build 94 for the first time and try to load a profile or change gender options

**Expected behavior**
  - The game to let the player load profiles or change gender options at the beginning

**Screenshots**
https://www.dropbox.com/s/x8mlxwve7cze3kp/domsim_crash.mp4?dl=0

**System (please complete the following information):**
 - VR Device: Valve index HMD and controllers, 2.0 light houses, 90 HZ refresh
 - Version: Build 94

**Additional context**
  Possibly tied to - Intro Goddess scene lock #81
 - After the initial crash this issue was not able to be replicated.
 - Another note is that unlike previous builds it did not seem to remember the gender options, and seemed to be back at default, this is even after starting it again after crash. When gender options are changed after crash, game closed, then re-opened the gender options are saved

**Comment by deviant-dev** [comment]
@Ropelopunny I think you might be right about this involving the save/load bugs from before. The save/load stuff was fixed up in build #95 and I'm not able to reproduce this one there.

**Comment by Ropelopunny** [comment]
Confirmed to be resolved in Build #95, closing
