### ISSUE TITLE
Vive Wand - No X button to use Journal

### ISSUE THREAD

**Issue by DevilishDomina** [deviant-dev/ds-issues#88]
**Describe the bug**
The Vive Wand does not have an X button and player could not progress without switching to Vive knuckles.

**To Reproduce**
Use Vive Wand controllers.

**Expected behavior**
ask DeviantDev if he is able to create a binding for Vive controllers even if he doesnt own them
sometimes the SteamVR binding only shows bindings for controller you ever connected to your pc

**Screenshots**

![image](https://user-images.githubusercontent.com/41113516/97134303-c4014580-17b1-11eb-86d0-5e507c774428.png)

**Comment by asphyxiachan** [comment]
Went in to look at this. The text is now Open Journal: Press 'X' or 'Menu'. Pressing Menu on Vive Wand seems to open the journal just fine.

**Comment by HeadphoneTaco** [comment]
Closing due to lack of further user complaints
