### ISSUE TITLE
Missing question prompt - intro Goddess scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#90]
**Describe the bug**
 - During the intro Goddess scene, the "...?" does not appear when the Goddess askes "I bet you have no idea where you are do you?"

**To Reproduce**
 - Play through the intro Goddess Scene

**Expected behavior**
   The "...?" should appear when the Goddess askes "I bet you have no idea where you are do you?"

**Screenshots**
![20201026122233_1](https://user-images.githubusercontent.com/60497088/97209382-a83a7700-1792-11eb-8362-49d4c98f0698.jpg)

**System (please complete the following information):**
 - VR Device: Valve Index HMD and controller, 2.0 light houses, 90 Hz
 - Version: 2.0.1

**Additional context**

**Comment by Ropelopunny** [comment]
Issue still in ver 2.0.4

**Comment by HeadphoneTaco** [comment]
Issue is not resolved, still occurring in current Master branch (Ver 2.0.8)

**Comment by ThatCuteEevee** [comment]
Issue validated as resolved in 2.1.0+139. Closing
