### ISSUE TITLE
Player repositioned - HM punishment scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#93]
Reported by elvis812 #1664 (Rockanrolla)

**Describe the bug**
 - During the Headmistress punishment, when I first went onto the desk, I was in the perfect position to kneel and get the spanking. However, when the spanking started, I was automatically repositioned closer to the back of the desk. Due to my limited play space, I wasn’t able to move forward to a better position so her hand when she spanked ended up in the middle of my back.

**To Reproduce**
 - Playing through HM punishment scene

**Expected behavior**
 - Player not to re-postioned during punishment scene

**Screenshots**
N/A

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - bug to be tested for duplication

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
