### ISSUE TITLE
Pose postion - HM reward scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#94]
Reported by elvis812 #1664 (Rockanrolla)

**Describe the bug**
  - During the Headmistress reward, when she asks if you want to perform standing or kneeling, the pose icon is not where I am and, in order to choose, I have to move forward and to the right. Normally, the pose icon is right where the player is but, in this case, it is forward and right of the players position.

**To Reproduce**
 - Play through head Mistress reward

**Expected behavior**
 For the pose indicator to appear in front of the player

**Screenshots**
 - N/A

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - bug to be tested for duplication

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)
