### ISSUE TITLE
HM dialog not playing - HM reward scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#95]
Reported by elvis812 #1664 (Rockanrolla)

**Describe the bug**
 When I the Headmistress reward started proper, she wasn’t saying anything. Normally she speaks her lines of encouragement. I waited a few minutes and then chose “Wait” from the Journal. After I did that, she continued her dialogue as usual.

**To Reproduce**
 - Play through the Head Mistress reward scene

**Expected behavior**
 For the HeadMistress dialog to play

**Screenshots**
 N/A

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - Workaround: Hitting wait in the journal ungags the Head Mistress
 - bug to be tested for duplication

**Comment by deviant-dev** [comment]
I wasn't able to reproduce this one. Might need to get Rockanrolla to record a video to help reproduce.

**Comment by rockanrolla** [comment]
This is @Rockanrolla. I had this issue a few versions back. I haven’t experienced it since in new versions. I believe it can be safely closed.

**Comment by Ropelopunny** [comment]
Was unable to verify in 2.0.4, player also confirms it is no longer reproduceable. Closing
