### ISSUE TITLE
Dice falling to floor and non-interactable - Nega reward Scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#96]
Reported by elvis812 #1664 (Rockanrolla)

**Describe the bug**
 During the Nega reward, I went in with a bloodstone five times and, every time I tried to grab the dice, they would fall to the floor. I had to use the Journal to continue.

**To Reproduce**
 - Roll the dice during the Head Mistress reward scene

**Expected behavior**
 - For the dice to roll and be re-rollable or for Nega to respond to the roll

**Screenshots**
https://drive.google.com/file/d/1g8fUV2sVjK3-_e18O-Jcl9QB5R--Cj3F/view#t=1m12s

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - bug to be tested for duplication

**Comment by deviant-dev** [comment]
It looks like this bug is about the dice falling onto the floor. Maybe the real bug is they aren't able to pick the dice up and roll them properly?

**Comment by Ropelopunny** [comment]
Ill check this out first, I know on 2.0.1 I was able to grab the dice and that issue was resolved, but its possible it re-apeared in 2.0.2

**Comment by Ropelopunny** [comment]
Issue still occurring in 2.0.8. Dice would be shaken and land on the floor but Nega would act like dice were not grabbed. had to use journal to continue. Additionally had trouble grabbing dice, currently looking for index owners to see if issue is tied to index controllers or if other controllers have same issue

**Comment by Ropelopunny** [comment]
case was not meant to be closed, re-opened

**Comment by HeadphoneTaco** [comment]
Issue is resolved, not occurring in current Master branch (Ver 2.0.8)

I was able to roll the dice, they did roll a little funny though.
