### ISSUE TITLE
Same reward multiple times in a row - Nega Reward scene

### ISSUE THREAD

**Issue by Ropelopunny** [deviant-dev/ds-issues#97]
**Describe the bug**
 During the Nega reward, no matter what I rolled, I got the same reward, which was licking the ground. I don’t remember all the rolls (Sorry, I should have written them down) but I know one was two skulls and a cup and one was two cups and a skull.

**To Reproduce**
 - Shaking the dice for reward during the Nega Yuki reward scene

**Expected behavior**
 The same scene should not play multiple times in a row

**Screenshots**
 N/A

**System (please complete the following information):**
 - VR Device: N/A
 - Version: 2.0.2

**Additional context**
 - bug to be tested for duplication

**Comment by DevilishDomina** [comment]
The code is working the way it's intended on the backend. We cannot reproduce this. We are getting variable scenes when playing. 

If this continues to persist, we need the player log so we can see what's going on in the code that isn't obvious.

**Comment by Ropelopunny** [comment]
Issue confirmed to be expected behavior from Domina, Closing
